NN modlue Notes : https://drive.google.com/file/d/130QErzy76HcLM4PncZJDx2HPF2QrB1AJ/view


In [0]:
!pip install torch

  Obtaining dependency information for torch from https://files.pythonhosted.org/packages/78/a9/97cbbc97002fff0de394a2da2cdfa859481fdca36996d7bd845d50aa9d8d/torch-2.6.0-cp311-cp311-manylinux1_x86_64.whl.metadata
  Obtaining dependency information for networkx from https://files.pythonhosted.org/packages/b9/54/dd730b32ea14ea797530a4479b2ed46a6fb250f682a9cfb997e968bf0261/networkx-3.4.2-py3-none-any.whl.metadata
  Obtaining dependency information for nvidia-cuda-nvrtc-cu12==12.4.127 from https://files.pythonhosted.org/packages/2c/14/91ae57cd4db3f9ef7aa99f4019cfa8d54cb4caa7e00975df6467e9725a9f/nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for nvidia-cuda-runtime-cu12==12.4.127 from https://files.pythonhosted.org/packages/ea/27/1795d86fe88ef397885f2e580ac37628ed058a92ed2c39dc8eac3adf0619/nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for nvidia-cuda-cupti-cu12==12

In [0]:
import torch  
import numpy as np 
import pandas as pd 
import torch.nn as nn

In [0]:
class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__() 
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()
    def forward(self,features):
        out = self.linear(features) 
        out=self.sigmoid(out) 
        return out 
    
   

In [0]:
features = torch.rand(10,5)
features

tensor([[0.8441, 0.9522, 0.4467, 0.1242, 0.9464],
        [0.0664, 0.4197, 0.4150, 0.8343, 0.2029],
        [0.4859, 0.5344, 0.7755, 0.7387, 0.8246],
        [0.7424, 0.2222, 0.5371, 0.0271, 0.5420],
        [0.8315, 0.5566, 0.7882, 0.0013, 0.8496],
        [0.3765, 0.2673, 0.8375, 0.2408, 0.8343],
        [0.8634, 0.0644, 0.9688, 0.4944, 0.9533],
        [0.8168, 0.1646, 0.6141, 0.7307, 0.3530],
        [0.9902, 0.4407, 0.5903, 0.0241, 0.1076],
        [0.6899, 0.7943, 0.1327, 0.3244, 0.7422]])

In [0]:
model=Model(features.shape[1])
model(features) 

tensor([[0.5691],
        [0.5214],
        [0.5783],
        [0.5765],
        [0.5876],
        [0.6024],
        [0.6223],
        [0.5527],
        [0.5191],
        [0.5547]], grad_fn=<SigmoidBackward0>)

to get model weights 

In [0]:
model.linear.weight

Parameter containing:
tensor([[-0.0122, -0.2529,  0.0246, -0.0513,  0.4028]], requires_grad=True)

In [0]:
model.linear.bias

Parameter containing:
tensor([0.1434], requires_grad=True)

In [0]:
!pip install torchinfo

  Obtaining dependency information for torchinfo from https://files.pythonhosted.org/packages/72/25/973bd6128381951b23cdcd8a9870c6dcfc5606cb864df8eabd82e529f9c1/torchinfo-1.8.0-py3-none-any.whl.metadata
Note: you may need to restart the kernel using %restart_python or dbutils.library.restartPython() to use updated packages.


In [0]:
from torchinfo import summary
summary(model,input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

Sequentiql container

In [0]:
import torch 
import numpy as np 
import pandas as pd 
import torch.nn as nn

In [0]:
class model(nn.Module):
    def __init__(self,num_features):
        super().__init__() 
        self.network=nn.Sequential(
            nn.Linear(num_features,10),
            nn.ReLU(),
            nn.Linear(10,1),
            nn.Sigmoid()
            )
    def forward(self,features):
        out=self.network(features)
        return out     

Real world example

In [0]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [0]:
df.shape

(569, 33)

In [0]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [0]:
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [0]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [0]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [0]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [0]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [0]:
X_train_tensor.shape

torch.Size([455, 30])

In [0]:
y_train_tensor.shape

torch.Size([455])

In [0]:
class model(nn.Module):
    def __init__(self,num_features):
        super(model, self).__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid= nn.Sigmoid()

    def forward(self, features):
        out= self.linear(features)
        out= self.sigmoid(out)
        return out 
    
    def loss_function(self, y_pred, y):

    # Clamp predictions to avoid log(0)
       epsilon = 1e-7
       y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
       loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
       return loss

In [0]:
learning_rate = 0.1
epochs = 25