Link to notes on intorduction to Pytorch 
link -https://drive.google.com/file/d/1OROYIk7ZNp980C68qcGv5mWGgq1FG-Vy/view


Why tensors are useful :

tensors are mulitdimentional arrays which are useful because :
1. Methamatically efficient -- Addn, subs, product, dot products are very efficient in tensors.
2. Representation -- Almost all form of data be it text,videos, images , int can be represent in the form of tensors.
3. Efficient computation ---Tensors can be easily optimized for hardware accelaration and GPU computation.


Where are tensors used in Deep learning !!

1. **Data storage** -- Text, image,video data is stored in the form of Tensors.
2. **Weights and biases** --- The learnable parameters of Neural network are stored in Weights and biases. 
3. **matrix operations** -- Neural Network invovle operation like dot product , transpose etc 
4. **Training process** --- During forward propogation ,tensors flow through the network, During backward propagation gradients are represented as Tensors. 

In [0]:
!pip install torch 

Note: you may need to restart the kernel using dbutils.library.restartPython() to use updated packages.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 766.7/766.7 MB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 21.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 9.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 253.1/253.1 MB 3.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 58.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 3.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 69.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 40.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 61.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 65.9 MB/s eta 0:00:00
     ━━━━

In [0]:
import torch 
print(torch.__version__)

2.6.0+cu124


Creating Tensors 

In [0]:
#Using Empty :
tensor = torch.empty(2,3)  #here 2,3 is shape 
tensor

tensor([[-2.8312e-11,  4.4022e-41, -2.8314e-11],
        [ 4.4022e-41,  6.4485e-23,  4.4023e-41]])

In [0]:
type(tensor)

torch.Tensor

In [0]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [0]:



torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [0]:




torch.rand(2,3)

tensor([[0.7303, 0.2100, 0.8100],
        [0.3650, 0.7190, 0.4145]])

In [0]:
#rand with seed :
torch.manual_seed(101)
torch.rand(2,3)

tensor([[0.1980, 0.4503, 0.0909],
        [0.8872, 0.2894, 0.0186]])

In [0]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [0]:
torch.linspace(0,10,5)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [0]:
torch.eye(5,5) #identity metrics 

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [0]:
torch.full((5,5), 10)

tensor([[10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10],
        [10, 10, 10, 10, 10]])

Tensor shapes 

In [0]:
x=torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

To get same size tensor 

In [0]:
torch.empty_like(x)

tensor([[7219329787328739874, 3472949507563676770, 3702864015914984758],
        [3834080850335785267, 3617058150078833250, 3180163871820166969]])

In [0]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [0]:
x.dtype

torch.int64

Tensor Data Types

In [0]:
x.dtype

torch.int64

In [0]:
torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

![test_image](/Workspace/Users/chintan.gehlot@meesho.com/Screenshot 2025-03-01 at 2.07.14 AM.png)

Mathematical operations 

1. Scaler operations 

In [0]:
!pip install torch

Note: you may need to restart the kernel using dbutils.library.restartPython() to use updated packages.
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 766.7/766.7 MB 1.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 150.1/150.1 MB 7.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 56.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.7/1.7 MB 65.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 56.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 48.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 19.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.2/6.2 MB 75.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 39.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.7/188.7 MB 3.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 1.7 MB/s eta 0:00:00
     ━━━━

In [0]:
import torch

In [0]:
m=torch.rand(2,2)
m

tensor([[0.4041, 0.9860],
        [0.6446, 0.5762]])

In [0]:
m+2


tensor([[2.4041, 2.9860],
        [2.6446, 2.5762]])

In [0]:
m-2 


tensor([[-1.5959, -1.0140],
        [-1.3554, -1.4238]])

In [0]:
m*2 


tensor([[0.8082, 1.9720],
        [1.2892, 1.1524]])

In [0]:
m/2 


tensor([[0.2021, 0.4930],
        [0.3223, 0.2881]])

In [0]:
m//2


tensor([[0., 0.],
        [0., 0.]])

In [0]:
m%2

tensor([[0.4041, 0.9860],
        [0.6446, 0.5762]])

In [0]:
m**2

tensor([[0.1633, 0.9722],
        [0.4155, 0.3320]])

2. Element wise operations 

In [0]:
a=torch.tensor([1,2,3]) 
b=torch.tensor([4,5,6]) 
print(a)
print(b)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [0]:
s=a+b 
print(s)
d=a-b 
print(d) 
mul=a*b 
print(mul)
div=a/b 
print(div)
power=a**b 
print(power)
mod=b%a
print(mod)

tensor([5, 7, 9])
tensor([-3, -3, -3])
tensor([ 4, 10, 18])
tensor([0.2500, 0.4000, 0.5000])
tensor([  1,  32, 729])
tensor([0, 1, 0])


In [0]:
c_m=torch.tensor([1,-2,3,-4]) 


In [0]:
#Absolutevalue 
torch.abs(c_m)

tensor([1, 2, 3, 4])

In [0]:
##negative 
torch.neg(c_m)

tensor([-1,  2, -3,  4])

In [0]:
dm=torch.tensor([1.5,9.8,3.0,4.8])
print(torch.round(dm)) 
print(torch.floor(dm))
print(torch.ceil(dm))

tensor([ 2., 10.,  3.,  5.])
tensor([1., 9., 3., 4.])
tensor([ 2., 10.,  3.,  5.])


In [0]:
#clamp ---Difingin min and max limit for specific usecase 
print(torch.clamp(dm,min=3,max=5))

tensor([3.0000, 5.0000, 3.0000, 4.8000])


Reduction Operation 

In [0]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[4., 6., 7.],
        [1., 7., 6.]])

In [0]:
# sum
print(torch.sum(e))
# sum along columns
print(torch.sum(e, dim=0))
# sum along rows
print(torch.sum(e, dim=1))

tensor(31.)
tensor([ 5., 13., 13.])
tensor([17., 14.])


In [0]:
print(torch.mean(e))
# mean along col
print(torch.mean(e, dim=0))

tensor(5.1667)
tensor([2.5000, 6.5000, 6.5000])


In [0]:
# median
torch.median(e)

tensor(6.)

In [0]:
# max and min
print(torch.max(e))
print(torch.min(e))

tensor(7.)
tensor(1.)


In [0]:
# product
torch.prod(e)

tensor(7056.)

In [0]:
# standard deviation
torch.std(e)

tensor(2.3166)

In [0]:
# variance
torch.var(e)

tensor(5.3667)

In [0]:
# argmax
torch.argmax(e) #returns the indeces of the max value of the tensor 

tensor(2)

In [0]:
# argmin
torch.argmin(e)

tensor(3)

Matrix Operations 

In [0]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

print(f)
print(g)

tensor([[7, 0, 7],
        [3, 9, 5]])
tensor([[7, 4],
        [2, 1],
        [3, 3]])


In [0]:
# matrix multiplcation
torch.matmul(f, g)

tensor([[70, 49],
        [54, 36]])

In [0]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
torch.dot(vector1, vector2)

tensor(11)

In [0]:
torch.transpose(f, 0, 1)

tensor([[7, 3],
        [0, 9],
        [7, 5]])

In [0]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[1., 3., 1.],
        [9., 4., 2.],
        [7., 9., 1.]])

In [0]:
# determinant
torch.det(h)

tensor(54.)

In [0]:
# inverse
torch.inverse(h)

tensor([[-0.2593,  0.1111,  0.0370],
        [ 0.0926, -0.1111,  0.1296],
        [ 0.9815,  0.2222, -0.4259]])

Comparision operator 

In [0]:
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[8, 0, 5],
        [5, 7, 7]])
tensor([[4, 0, 7],
        [4, 2, 5]])


In [0]:
# greater than
print(i > j)
# less than
print(i < j)
# equal to
print(i == j)
# not equal to
print(i != j)
# greater than equal to
print(i >= j)
# less than equal to 
print(i <= j)

tensor([[ True, False, False],
        [ True,  True,  True]])
tensor([[False, False,  True],
        [False, False, False]])
tensor([[False,  True, False],
        [False, False, False]])
tensor([[ True, False,  True],
        [ True,  True,  True]])
tensor([[ True,  True, False],
        [ True,  True,  True]])
tensor([[False,  True,  True],
        [False, False, False]])


Special Function 


In [0]:
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
print(torch.log(k))
print(torch.exp(k))
print(torch.sqrt(k))
print(torch.sigmoid(k))
print(torch.tanh(k))
print(torch.relu(k))
print(torch.softmax(k, dim=1)) # we needt to spacify weather we have to do sum Ex at row level or column level

tensor([[2.1972, 1.0986, 1.0986],
        [  -inf, 2.0794, 1.3863]])
tensor([[8.1031e+03, 2.0086e+01, 2.0086e+01],
        [1.0000e+00, 2.9810e+03, 5.4598e+01]])
tensor([[3.0000, 1.7321, 1.7321],
        [0.0000, 2.8284, 2.0000]])
tensor([[0.9999, 0.9526, 0.9526],
        [0.5000, 0.9997, 0.9820]])
tensor([[1.0000, 0.9951, 0.9951],
        [0.0000, 1.0000, 0.9993]])
tensor([[9., 3., 3.],
        [0., 8., 4.]])
tensor([[9.9507e-01, 2.4665e-03, 2.4665e-03],
        [3.2932e-04, 9.8169e-01, 1.7980e-02]])


Inplace Operations

In [0]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

tensor([[0.2924, 0.7244, 0.2842],
        [0.5530, 0.5156, 0.1524]])
tensor([[0.9051, 0.6572, 0.6721],
        [0.8625, 0.1440, 0.7891]])


In [0]:
m.add_(n) #underscore tells that you want to do inplace operation

tensor([[2.1026, 2.0387, 1.6283],
        [2.2780, 0.8036, 1.7306]])

In [0]:
m

tensor([[2.1026, 2.0387, 1.6283],
        [2.2780, 0.8036, 1.7306]])

In [0]:
torch.relu(m)

tensor([[2.1026, 2.0387, 1.6283],
        [2.2780, 0.8036, 1.7306]])

In [0]:
m.relu_()

tensor([[2.1026, 2.0387, 1.6283],
        [2.2780, 0.8036, 1.7306]])

In [0]:
m

tensor([[2.1026, 2.0387, 1.6283],
        [2.2780, 0.8036, 1.7306]])

Copying a Tensor

In [0]:
a = torch.rand(2,3)
a

tensor([[0.1852, 0.1976, 0.9445],
        [0.4154, 0.2561, 0.9615]])

In [0]:
b = a

In [0]:
b

tensor([[0.1852, 0.1976, 0.9445],
        [0.4154, 0.2561, 0.9615]])

In [0]:
a[0][0] = 0
a

tensor([[0.0000, 0.1976, 0.9445],
        [0.4154, 0.2561, 0.9615]])

In [0]:
b

tensor([[0.0000, 0.1976, 0.9445],
        [0.4154, 0.2561, 0.9615]])

In [0]:
#memory locations 
id(a) , id(b)

(136114796261312, 136114796261312)

In [0]:
c = a.clone()

In [0]:
a[0][0] = 1
a

tensor([[1.0000, 0.1976, 0.9445],
        [0.4154, 0.2561, 0.9615]])

In [0]:
c

tensor([[0.0000, 0.1976, 0.9445],
        [0.4154, 0.2561, 0.9615]])

In [0]:
id(a),id(c)

(136114796261312, 136114792739872)