In [0]:
!pip install torch 

  Obtaining dependency information for torch from https://files.pythonhosted.org/packages/78/a9/97cbbc97002fff0de394a2da2cdfa859481fdca36996d7bd845d50aa9d8d/torch-2.6.0-cp311-cp311-manylinux1_x86_64.whl.metadata
  Obtaining dependency information for networkx from https://files.pythonhosted.org/packages/b9/54/dd730b32ea14ea797530a4479b2ed46a6fb250f682a9cfb997e968bf0261/networkx-3.4.2-py3-none-any.whl.metadata
  Obtaining dependency information for nvidia-cuda-nvrtc-cu12==12.4.127 from https://files.pythonhosted.org/packages/2c/14/91ae57cd4db3f9ef7aa99f4019cfa8d54cb4caa7e00975df6467e9725a9f/nvidia_cuda_nvrtc_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for nvidia-cuda-runtime-cu12==12.4.127 from https://files.pythonhosted.org/packages/ea/27/1795d86fe88ef397885f2e580ac37628ed058a92ed2c39dc8eac3adf0619/nvidia_cuda_runtime_cu12-12.4.127-py3-none-manylinux2014_x86_64.whl.metadata
  Obtaining dependency information for nvidia-cuda-cupti-cu12==12

In [0]:
import torch  
import numpy as np 
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler 
from sklearn.preprocessing import LabelEncoder 


In [0]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0    842302         M  ...                  0.11890          NaN
1    842517         M  ...                  0.08902          NaN
2  84300903         M  ...                  0.08758          NaN
3  84348301         M  ...                  0.17300          NaN
4  84358402         M  ...                  0.07678          NaN

[5 rows x 33 columns]

In [0]:
df.shape

(569, 33)

In [0]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [0]:
df.drop('id', axis=1, inplace=True)
df.drop('Unnamed: 32', axis=1, inplace=True)
df.head()

diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0         M        17.99  ...          0.4601                  0.11890
1         M        20.57  ...          0.2750                  0.08902
2         M        19.69  ...          0.3613                  0.08758
3         M        11.42  ...          0.6638                  0.17300
4         M        20.29  ...          0.2364                  0.07678

[5 rows x 31 columns]

In [0]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

In [0]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [0]:
X_train

array([[ 0.02159095,  0.307334  ,  0.01910884, ...,  0.29569843,
        -0.58390759, -0.27327743],
       [-0.6289414 ,  0.46045938, -0.63567782, ..., -0.48404516,
         0.29878136, -0.55552447],
       [ 1.07764997,  0.18291962,  0.90973314, ...,  0.06148639,
         3.24706036, -1.2458328 ],
       ...,
       [ 1.81829936,  0.69254003,  1.74763117, ...,  1.17931659,
         0.0279378 , -1.38278106],
       [-1.24004755, -0.24535292, -1.27575018, ..., -1.74072964,
        -1.60364991, -0.99643108],
       [-0.80635932,  0.13985311, -0.84372177, ..., -1.31002282,
        -0.54638107, -0.409669  ]])

In [0]:
y_train

476    B
415    B
119    M
461    M
525    B
      ..
503    M
87     M
210    M
192    B
522    B
Name: diagnosis, Length: 455, dtype: object

In [0]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [0]:
y_train

array([0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,

Numpy arrays to pytorch tensors 

In [0]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

Defining model 

In [0]:
class MySimpleNN():
    def __init__(self, X):
        self.weights=torch.rand(X.shape[1], 1,dtype=torch.float64,requires_grad=True)
        self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)  
         
    def forward(self,X):
        z=torch.matmul(X,self.weights)+self.bias 
        y_pred=torch.sigmoid(z)
        return y_pred
    

    def loss_function(self, y_pred, y):

    # Clamp predictions to avoid log(0)
       epsilon = 1e-7
       y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
       loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
       return loss
       

In [0]:
lr=0.1 
epoch=25

training pipeline 

In [0]:
model=MySimpleNN(X_train_tensor)
model.weights

tensor([[0.9807],
        [0.5405],
        [0.2504],
        [0.9820],
        [0.9387],
        [0.6388],
        [0.0707],
        [0.9693],
        [0.6294],
        [0.0534],
        [0.3881],
        [0.9595],
        [0.9458],
        [0.8035],
        [0.3511],
        [0.6184],
        [0.3478],
        [0.3392],
        [0.1229],
        [0.8604],
        [0.5998],
        [0.2276],
        [0.6573],
        [0.2151],
        [0.4758],
        [0.0431],
        [0.9710],
        [0.3126],
        [0.8247],
        [0.9541]], dtype=torch.float64, requires_grad=True)

In [0]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [0]:
#defining loop 
for i in range(0,epoch):
    #forward pass
    y_pred=model.forward(X_train_tensor)
    #loss calc 
    loss=model.loss_function(y_pred,y_train_tensor)
    #gradient descent 
    loss.backward() 
    #weight update
     # parameters update
    with torch.no_grad():

        model.weights -= lr * model.weights.grad
        model.bias -= lr * model.bias.grad 

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()    

     # print loss in each epoch
    print(f'Epoch: {i + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.6774922535529337
Epoch: 2, Loss: 0.6773088290207345
Epoch: 3, Loss: 0.6771301296393366
Epoch: 4, Loss: 0.6769559587976474
Epoch: 5, Loss: 0.676786130812501
Epoch: 6, Loss: 0.6766204702079431
Epoch: 7, Loss: 0.6764588110473643
Epoch: 8, Loss: 0.6763009963143627
Epoch: 9, Loss: 0.6761468773385385
Epoch: 10, Loss: 0.6759963132627241
Epoch: 11, Loss: 0.6758491705484403
Epoch: 12, Loss: 0.6757053225166206
Epoch: 13, Loss: 0.6755646489208855
Epoch: 14, Loss: 0.6754270355508689
Epoch: 15, Loss: 0.6752923738632938
Epoch: 16, Loss: 0.6751605606386872
Epoch: 17, Loss: 0.6750314976617873
Epoch: 18, Loss: 0.674905091423854
Epoch: 19, Loss: 0.6747812528452393
Epoch: 20, Loss: 0.6746598970166997
Epoch: 21, Loss: 0.6745409429580612
Epoch: 22, Loss: 0.6744243133929506
Epoch: 23, Loss: 0.6743099345384117
Epoch: 24, Loss: 0.6741977359083208
Epoch: 25, Loss: 0.6740876501295961


In [0]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}') 

Accuracy: 0.6132656335830688
